//This file was generated by script swreg2regmap.py


//registers width
`define TIMER_RESET_W 1
`define TIMER_ENABLE_W 1
`define TIMER_SAMPLE_W 1
`define TIMER_DATA_HIGH_W DATA_W
`define TIMER_DATA_LOW_W DATA_W
