//This file was generated by script swreg2regmap.py

//address macros
`define TIMER_RESET_ADDR 0
`define TIMER_ENABLE_ADDR 1
`define TIMER_SAMPLE_ADDR 2
`define TIMER_DATA_HIGH_ADDR 3
`define TIMER_DATA_LOW_ADDR 4


//write registers
`REG_ARE(clk, rst, 0, valid & wstrb & (address == 0), TIMER_RESET, wdata[1-1:0])
`REG_ARE(clk, rst, 0, valid & wstrb & (address == 1), TIMER_ENABLE, wdata[1-1:0])
`REG_ARE(clk, rst, 0, valid & wstrb & (address == 2), TIMER_SAMPLE, wdata[1-1:0])


//read registers
`SIGNAL(rdata_int,`DATA_W)
`SIGNAL2OUT(rdata, rdata_int)

always @* begin
   rdata_int = `DATA_W'd0;
   case(address)
     3: rdata_int = TIMER_DATA_HIGH | `DATA_W'd0;
     4: rdata_int = TIMER_DATA_LOW | `DATA_W'd0;
     default: rdata_int = `DATA_W'd0;
   endcase
end
